[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sci-viewer-demo-plugin"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "sci-viewer-server>=0.1",
]

[project.entry-points."sci_viewer_srv.plugins"]
demo = "demo:create_plugin"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
