import * as THREE from 'three';
import _ from 'lodash';
import * as Geometry from './geometry';
import * as Shaders from "./shaders";
import * as Materials from './materials';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
import { LineMaterial } from 'three/addons/lines/LineMaterial.js';
//import { TrackballControls } from 'three/examples/jsm/controls/TrackballControls';
import { watch } from 'vue';
import * as Utils from './utils';
import * as HlOverlay from './hl-overlay';
//import { getGPUTier } from "detect-gpu";

//                  * * *   * * *   * * *

// Produced event display ID to identify created event objects representations.
// Note, that it differs from the IDs used in event's main API to identify
// particular event data.
export function make_evdsp_id(type, evID, item) {
    // TODO: check `type' is within permitted collections names
    if(item.hasOwnProperty('$k') && item.hasOwnProperty('$n')) {
        return `/${evID.runNo}-${evID.spill}-${evID.eventInSpill}/${type}/${item['$k']}[${item['$n']}]`;
    } else if( item.hasOwnProperty('$k') ) {
        return `/${evID.runNo}-${evID.spill}-${evID.eventInSpill}/${type}/${item['$k']}`;
    } else if( item.hasOwnProperty('$n') ) {
        return `/${evID.runNo}-${evID.spill}-${evID.eventInSpill}/${type}[${item['$n']}]`;
    } else {
        throw new Error('Item does not provide "$k" or "$n"');
    }
}

// Parses representation object ID previously generated by `make_evdsp_id()`
export function parse_evdsp_id(s) {
    const rx = /\/(\d+)-(\d+)-(\d+)\/([^\/]+)\/([^\[]+)?([^\]+]+)?/;
    const m = s.match(rx);
    if(!m) {
        throw new Error(`String "${s}" does not match the pattern of evDsp-ID.`);
    }
    return {
        eventID: { runNo: m[1], spill: m[2], eventInSpill: m[3] },
        type: m[4],
        k: m[5],
        n: m[6],
    };
}

//                  * * *   * * *   * * *

/* Event display class
 *
 * Maintains scope with objects responsible for displaying the data. */
class ThreeView {
    // Creates and returns perspective camera + orbit controls
    _create_persp_camera(cfg) {  // {{{
        cfg.aspect = this._container.clientWidth / this._container.clientHeight;  // TODO
        const cam = new THREE.PerspectiveCamera( cfg.fov
                , cfg.aspect
                , cfg.cuts[0], cfg.cuts[1]
                );
        cam.position.set( cfg.position[0], cfg.position[1], cfg.position[2] );

        // normal camera sees only normal layer:
        cam.layers.enable(Utils.LAYER_MAIN);
        cam.layers.disable(Utils.LAYER_MASK_SELECTED);
        cam.layers.disable(Utils.LAYER_MASK_HIGHLIGHTED);

        // create new control
        const controls = new OrbitControls(cam, this._container);
        controls.addEventListener( 'change', () => {
                this._update();
                this._render();
            } );
        controls.enabled = false;

        return [cam, controls];
    }  // }}}
    // Creates and returns orthograpic camera + orbit controls
    _create_ortho_camera(cfg) {  // {{{
        const aspect = this._container.clientWidth
                     / this._container.clientHeight
                     ;
        const halfHeight = cfg.width/(2*aspect);
        const cam = new THREE.OrthographicCamera(
                    -cfg.width/2, cfg.width/2, // left, right
                    -halfHeight, halfHeight, // top, bottom
                    cfg.cuts[0], cfg.cuts[1]  // near, far
                    );
        cam.position.set( cfg.lookAt[0], cfg.lookAt[1], cfg.lookAt[2] );
        cam.up.set(cfg.up[0], cfg.up[1], cfg.up[2]);
        // ...

        // normal camera sees only normal layer:
        cam.layers.enable(Utils.LAYER_MAIN);
        cam.layers.disable(Utils.LAYER_MASK_SELECTED);
        cam.layers.disable(Utils.LAYER_MASK_HIGHLIGHTED);

        // create new control
        const controls = new OrbitControls(cam, this._container);
        //const controls = new TrackballControls(cam, this._container);
        controls.addEventListener( 'change', () => {
                this._update();
                this._render();
            } );
        controls.mouseButtons = {
            LEFT: THREE.MOUSE.PAN,
            MIDDLE: THREE.MOUSE.DOLLY,
            RIGHT: THREE.MOUSE.ROTATE
        }
        cam.updateProjectionMatrix();
        //controls.screenSpacePanning = true;
        controls.enabled = false;

        return [cam, controls];
    }  // }}}
    _create_lights() {  // {{{
        // TODO: themed?
        const mainLight = new THREE.DirectionalLight(0xffffff, 5);
        mainLight.position.set(10, 10, 10);

        const hemisphereLight = new THREE.HemisphereLight(0x99aaee, 0x202020, 5);
        this._scene.add(mainLight, hemisphereLight);
    }  // }}}
    _create_static_meshes() { // {{{
        // create axes helper; perhaps to be removed at some point
        //const axesHelper = new THREE.AxesHelper( 5 );
        //this._scene.add( axesHelper );
        // create grid helper; to be removed?
        const theme = Utils.get_theme();
        const gridHelper = new THREE.GridHelper(5000, 50, theme.grid1, theme.grid2);
        this._scene.add( gridHelper );
        // xxx:
        //const markers = get_markers();
        //const sprite = new THREE.Sprite( markers['whiteCircle-10x10'] );
        //this._scene.add( sprite );
    }  // }}}
    _create_renderer() {  // {{{
        this._renderer = new THREE.WebGLRenderer({ antialias: true });  // TODO: option?
        this._renderer.setSize( this._container.clientWidth
                              , this._container.clientHeight
                              );
        this._renderer.setPixelRatio( window.devicePixelRatio );
        //this._renderer.gammaFactor = 2.2;  // deprecated?
        this._renderer.gammaOutput = true;
        this._renderer.physicallyCorrectLights = true;
        this._container.appendChild(this._renderer.domElement);
    }  // }}}
    _update() {  // {{{
        const c = this._camctrls[this._cfg.currentCamera];
        const dest = this._cfg.cameras[this._cfg.currentCamera];
        if(dest['type'] == 'persp') {
            const pos = c[0].position;
            // update position
            dest.position[0] = pos.x; dest.position[1] = pos.y; dest.position[2] = pos.z;
            // update lookup
            const lat = c[1].target;
            dest.lookAt[0] = lat.x; dest.lookAt[1] = lat.y; dest.lookAt[2] = lat.z;
            dest.fov = c[0].fov;
        } else if(dest['type'] == 'ortho') {
            const pos = c[0].position;
            dest.position[0] = pos.x; dest.position[1] = pos.y; dest.position[2] = pos.z;
            const lat = c[1].target;
            dest.lookAt[0] = lat.x; dest.lookAt[1] = lat.y; dest.lookAt[2] = lat.z;
            dest.width = c[0].right - c[0].left;
            dest.cuts[0] = c[0].near;  dest.cuts[1] = c[0].far;
            dest.up[0] = c[0].up.x; dest.up[1] = c[0].up.y; dest.up[2] = c[0].up.z;
        }
    }  // }}}
    _render(maskUpdate=true) {  // {{{
        this._renderer.setRenderTarget(null);
        this._renderer.render(this._scene, this.get_cam());
        if(maskUpdate && (this._hoverHL || this._selectHL)) {
            // TODO: check we have highlights/selection
            const oldClearColor = new THREE.Color();
            this._renderer.getClearColor(oldClearColor);
            const oldClearAlpha = this._renderer.getClearAlpha();
            const oldBackground = this._scene.background;
            this._scene.background = null;

            const oldMask = this.get_cam().layers.mask;
            if(this._hoverHL)  
                this._hoverHL.render(this._renderer, this.get_cam(), this._scene);
            if(this._selectHL)
                this._selectHL.render(this._renderer, this.get_cam(), this._scene);
            this.get_cam().layers.mask = oldMask;

            this._renderer.setRenderTarget(null);
            this._renderer.setClearColor(oldClearColor, oldClearAlpha);
            this._scene.background = oldBackground;
        }
    } // }}}
    _update_persp_camera(newCfg, camName) {  // {{{
        this._camctrls[camName][0].fov    = newCfg.fov;
        this._camctrls[camName][0].near   = newCfg.cuts[0];
        this._camctrls[camName][0].far    = newCfg.cuts[1];
        this._camctrls[camName][0].position.set( newCfg.position[0]
                                               , newCfg.position[1]
                                               , newCfg.position[2]
                                               );
        this._camctrls[camName][0].aspect = newCfg.aspect;
        this._camctrls[camName][0].lookAt( newCfg.lookAt[0]
                                         , newCfg.lookAt[1]
                                         , newCfg.lookAt[2]
                                         );
        this._camctrls[camName][1].target.set( newCfg.lookAt[0]
                                             , newCfg.lookAt[1]
                                             , newCfg.lookAt[2]
                                             );
        this._camctrls[camName][1].update();
        this._camctrls[camName][0].updateProjectionMatrix();
        this._render();
    }  // }}}
    _update_ortho_camera(newCfg, camName) {  // {{{
        const aspect = this._container.clientWidth
                     / this._container.clientHeight;
        const halfHeight = newCfg.width/(2*aspect);
        this._camctrls[camName][0].left     = -newCfg.width/2;
        this._camctrls[camName][0].right    =  newCfg.width/2;
        this._camctrls[camName][0].top      = -halfHeight;
        this._camctrls[camName][0].bottom   =  halfHeight;
        this._camctrls[camName][0].near     = newCfg.cuts[0];
        this._camctrls[camName][0].far      = newCfg.cuts[1];

        this._camctrls[camName][0].up.set(newCfg.up[0], newCfg.up[1], newCfg.up[2]);
        this._camctrls[camName][0].lookAt(newCfg.lookAt[0], newCfg.lookAt[1], newCfg.lookAt[2]);
        this._camctrls[camName][1].target.set(newCfg.lookAt[0], newCfg.lookAt[1], newCfg.lookAt[2]);

        this._camctrls[camName][0].updateProjectionMatrix();
        this._render();
    }  // }}}
    _bind_watchers() {  // {{{
        // NOTE: use getter here instead of plain reactive var
        // camera (view) switch
        watch( () => this._cfg.currentCamera
             , newCam => this._switch_cam(newCam)
             );
        // Camera position watcher
        Object.entries(this._cfg.cameras).forEach(([camName, camCfg]) => {
            if(camCfg.type == "persp") {
                watch( () => this._cfg.cameras[camName]
                     , newCfg => this._update_persp_camera(newCfg, camName)
                     , {deep:true} );
            } else if(camCfg.type == "ortho") {
                watch( () => this._cfg.cameras[camName]
                     , newCfg => this._update_ortho_camera(newCfg, camName)
                     , {deep:true} );
            }
        });

        // Geometry update watcher
        //  This function is triggered on either geometry data indexed by source
        //  name gets updated, global transformation matrix gets changed, list
        //  of drawn items changed, etc.
        watch( [ () => this._vuexStore.getters['view3D/geoData']
               , () => this._vuexStore.getters['view3D/transformationMatrix']
               ]
            , this.update_drawables.bind(this) );  // end of watcher

        // Highlighted items updater
        watch( () => this._vuexStore.getters['view3D/highlightedGeoItemIDs']
            , (hlItems, hlItemsOld) => this.update_highlighted_graphics(hlItems, hlItemsOld)
            );
        // Selected items updater
        watch( () => this._vuexStore.getters['view3D/selectedGeoItemIDs']
            , (hlItems, hlItemsOld) => this.update_selected_graphics(hlItems, hlItemsOld)
            );
        // Highlighted markers
        watch( () => this._vuexStore.getters['view3D/highlightedMarkers']
            , (hlMarkers) => this.update_highlighted_markers(hlMarkers)
            );
    }  // _bind_watchers() }}}
    // Called on camera switch; see explaination for _prevCam in ctr
    _switch_cam( newCam ) {  // {{{
        if(this._prevCam)
            this._camctrls[this._prevCam][1].enabled = false;
        this._camctrls[newCam][1].enabled = true;
        this._prevCam = newCam;
        this._render();
    }  // }}}
    // Creates default materials expected across API
    _create_default_materials() {  // {{{
        // NOTE: these are not all the default ones used to create geometries,
        // some others are created in the highlighting overlays.
        this._defaultMaterials['defaultMeshMaterial'] = new THREE.MeshBasicMaterial({
                color: Utils.get_theme().foreground,
                side: THREE.DoubleSide,
                transparent: true,
                opacity: 0.15
            });

        this._defaultMaterials['defaultLineMaterial'] = new THREE.LineBasicMaterial({
                color: Utils.get_theme().foreground,
            });

        this._defaultMaterials['defaultFatLineMaterial'] = new LineMaterial({
                color: Utils.get_theme().foreground,
                linewidth: 5
            });
    }  // }}}
    // Creates fixture to render things using three.js
    constructor(container, cfgObj, vuexStore, highlightOnHover=true, highlightOnSelection=true) {  // {{{
        //const gpu = getGPUTier();
        //console.log(gpu);
        // Vue's `watch()' for `reactive' object does not provide previous
        // state of watched object, but when we switch camera we have to
        // disable previous controls, so this cache is needed
        this._prevCam = null;
        this._cfg = cfgObj;
        this._vuexStore = vuexStore;
        this._container = container;
        // Default materials
        this._defaultMaterials = {};
        // Index of materials by source ID {<sourceID:str>:Object}
        // Where object item is <materialName:str>:{threeJSMaterial, matDef}
        // One can compare 2nd
        this._materials = {};
        // Geometries, of similar structure to materials:
        //  {<sourceID:str>:Object}, where Object is
        //      {threeJSGeo, geoDef, geoMaterial, geoType}
        this._geometries = {};
        // create raycaster and pointer vec
        this._pointer = new THREE.Vector2();
        this._raycaster = new THREE.Raycaster();
        //this._raycaset.threshold = 5.0;  // world units unfortunately
        // Creating the (main) scene
        this._scene = new THREE.Scene();
        this._scene.background = new THREE.Color(Utils.get_theme().background);
        // Create cameras, one per entry
        this._camctrls = Object.fromEntries(Object.entries(this._cfg.cameras).map(([camName, camCfg], i) => {
                if(camCfg.type === 'persp') {
                    return [camName, this._create_persp_camera(camCfg)];
                }
                if(camCfg.type === 'ortho') {
                    return [camName, this._create_ortho_camera(camCfg)];
                }
            }));
        this._create_lights();
        this._create_static_meshes();
        this._create_renderer();
        this._create_default_materials();
        this._switch_cam(this._cfg.currentCamera);
        this._render();

        // TODO: add error handlers to this object; useful for debugging
        this._textureLoader = new THREE.TextureLoader();
        this._bind_watchers();

        const w = this._container.clientWidth;
        const h = this._container.clientHeight;
        if(highlightOnHover)
            this._hoverHL = new HlOverlay.SilhouetteOverlay(Utils.LAYER_MASK_HIGHLIGHTED
                    , w, h, Utils.get_theme().highlight
                    , null  // enables debug quad; possible options: 'mask', 'dilate'
                    );
        if(highlightOnSelection)
            this._selectHL = new HlOverlay.SilhouetteOverlay(Utils.LAYER_MASK_SELECTED
                    , w, h, Utils.get_theme().selected
                    , null  // enables debug quad; possible options: 'mask', 'dilate'
                    );
    }  // }}}
    // Raycasting pointer
    update_pointer(event) {  // {{{
        this._pointer.x = ( event.clientX / this._container.clientWidth ) * 2 - 1;
	    this._pointer.y = - ( event.clientY / this._container.clientHeight ) * 2 + 1;
        // update picking ray with camera and pointer position
        this._raycaster.setFromCamera(this._pointer, this.get_cam());
        // get the intersecting objects
        const intersects = this._raycaster.intersectObjects( this._scene.children, true );
        const items2highlight = intersects.filter(item => item.object.userData?.pickable );
        const markers2highlight = intersects.filter(item => (item.object.userData?.pickable
                    && item.object.userData?.isPointCloud));
        let hasSome = false;
        if(items2highlight && items2highlight.length) {
            const ids2highlight = items2highlight.map(item => Utils.full_geo_id(
                    item.object.userData.srcID, item.object.userData.geoID));
            this._vuexStore.commit('view3D/set_scene_hover_geo_items', ids2highlight);
            hasSome = true;
        }
        if(markers2highlight && markers2highlight.length) {
            const ids2highlight = items2highlight.map(item =>
                    [ Utils.full_geo_id(item.object.userData.srcID, item.object.userData.geoID)
                    , item.index
                    ]
                );
            const ptsByGeo = new Map();
            for(const [geoID, idx] of ids2highlight) {
                if(!ptsByGeo.has(geoID)) ptsByGeo.set(geoID, new Set());
                ptsByGeo.get(geoID).add(idx);
            }
            this._vuexStore.commit('view3D/set_highlighted_markers', ptsByGeo);
            hasSome = true;
        }
        if(!hasSome) {
            this._vuexStore.commit('view3D/clear_scene_hover_geo_items');
        }
    }  // }}}
    get_cam() {  // {{{
        return this._camctrls[this._cfg.currentCamera][0];
    }  // }}}
    on_resize() {  // {{{
        const w = this._container.clientWidth;
        const h = this._container.clientHeight;
        this._cfg.cameras.persp1.aspect = w/h;  // ?
        this._renderer.setSize(w, h);
        // this is required for this kind of materials
        this._defaultMaterials['defaultFatLineMaterial'].resolution.set(w, h);
        if(this._hoverHL)
            this._hoverHL.notify_resized(w, h);
        if(this._selectHL)
            this._selectHL.notify_resized(w, h);
    }  // }}}
    update_drawables() {  // {{{
        console.debug('"geometry updated" hook triggered in ThreeViewer');
        // use values from this._vuexStore.getters['view3D/geoData']
        // to re-draw the scene. Take into account items disabled for
        // drawing
        Object
            .entries(this._vuexStore.getters['view3D/geoData'])
            .map(([sourceName, geoData]) => this.update_drawables_from_source(sourceName, geoData));
        this._render();
    }  // }}}
    // Creates/updates item by its geometrical definition; assumes materials
    // and geometrical definitions are scoped by the source (should be
    // forwarded by `thisSourceMats` and `thisSourceGeo`).
    update_geometry_item(geoDef_, geomNamesInUse, thisSourceMats, thisSourceID, thisSourceGeo) {  // {{{
        const { _name: geoName
              , _type: geoType
              , _material: geoMaterial
              , ...geoDef } = geoDef_;
        if(geomNamesInUse.has(geoName)) {
            throw new Error(`Geometry name "${geoName}" met`
                + ` at least twice for source "${sourceName}"`);
        }
        geomNamesInUse.add(geoName);
        // pop position and rotation properties, if
        // provided, as we shall not re-create object on
        // its change
        var position = null;
        if( geoDef.position ) {
            position = geoDef.position;
            delete geoDef.position;
        }
        var rotation = null;
        if( geoDef.rotation ) {
            rotation = geoDef.rotation;
            delete geoDef.rotation;
        }
        var rotationOrder = null;
        if( geoDef.rotation ) {
            rotationOrder = geoDef.rotationOrder;
            delete geoDef.rotationOrder;
        }
        // try to get material
        if(!( thisSourceMats.hasOwnProperty(geoMaterial)
            || this._defaultMaterials.hasOwnProperty(geoMaterial)
            )) {
            console.error(`Error in geometry "${geoName}":`
                + ` materials set "${geoMaterial}" is not defined`
                + ` by data source "${thisSourceID}"; geometry`
                + " not constructed!" );
            return;
        }
        if(thisSourceGeo.hasOwnProperty(geoName)) {  // eponymous geo item exists
            if( _.isEqual(thisSourceGeo[geoName].geoDef, geoDef)
             && geoMaterial == thisSourceGeo[geoName].geoMaterial
             && geoType == thisSourceGeo[geoName].geoType
              ) {  // geometry definition and material did not change (position/rotation can)
                if(!thisSourceGeo[geoName].hasOwnProperty('threeJSGeo')) {
                    console.warn(`Can't check/update geometry record ${geoName} as it does not expose its three.js representation`);
                    return;
                }
                console.debug(`Geometry "${sourceName}/${geoName}" unchanged, updating position and rotation`);
                // yet, position/rotation may change
                if(position !== null ) {
                    if(thisSourceGeo[geoName].threeJSGeo.hasOwnProperty('position'))
                        thisSourceGeo[geoName].threeJSGeo.position.set(...position);
                    else
                        console.warn(`Can not update position for geometry item ${geoName} as it does not expose 'position' property`)
                }
                if(thisSourceGeo[geoName].threeJSGeo.hasOwnProperty('rotation')) {
                    if(rotationOrder != null ) {
                        thisSourceGeo[geoName].threeJSGeo.rotation.order = rotationOrder;
                    }
                    if(rotation !== null) {
                        thisSourceGeo[geoName].threeJSGeo.rotation.set(...rotation);
                    }
                } else {
                    console.warn(`Can not update position for geometry item ${geoName} as it does not expose 'rotation' property`)
                }
                return;  // skip geometry construction
            }
            // otherwise, destroy existing eponymous geometry record (to
            // substitute below)
            thisSourceGeo[geoName].threeJSGeo.dispose(); // TODO: is it correct?
            // ^^^ https://discourse.threejs.org/t/correctly-remove-mesh-from-scene-and-dispose-material-and-geometry/5448
        }
        console.debug(`Creating geometry item "${geoName}" of type ${geoType}...`);
        const geometryCreationContext = {
                  defaultMeshMaterial:      this._defaultMaterials.defaultMeshMaterial
                , defaultLineMaterial:      this._defaultMaterials.defaultLineMaterial

                //, pointsMaskMaterial:       ,
                , lineMaskMaterial:         HlOverlay.SilhouetteOverlay.lineMaskMaterial
                , meshMaskMaterial:         HlOverlay.SilhouetteOverlay.meshMaskMaterial
            };  // context;
        const threeJSGeo = Geometry.make_geometry( geoType  // geo type name string (one of geometry/*.js)
                , thisSourceMats.hasOwnProperty(geoMaterial)
                ? thisSourceMats[geoMaterial].threeJSMaterials
                : { base: this._defaultMaterials[geoMaterial]
                  , mask: null
                  }  // materials for the item
                , geoDef  // geometry definition object as provided
                , {geoID: geoName, srcID: thisSourceID}  // userdata to save in the three.js group object, shallow-copied
                , geometryCreationContext // context
            );
        this._scene.add(threeJSGeo);

        if(position !== null) {
            console.debug(`Placing new geometry at ${position[0]}x${position[1]}x${position[2]}`);
            threeJSGeo.position.set(...position);
        }
        if(rotationOrder != null) {
            thisSourceGeo[geoName].rotation.order = rotationOrder;
        }
        if(rotation !== null) {
            console.debug(`Rotating new geometry by ${rotation[0]},${rotation[1]},${rotation[2]}`);
            threeJSGeo.rotation.set(...rotation);
        }
        // Push item to the global collection
        thisSourceGeo[geoName] = {threeJSGeo, geoDef, geoMaterial, geoType};
    }  // }}}
    // (Re)creates geometry items defined by `geoData' parameter including
    // materials and drawable objects (point markers, lines, meshes, etc).
    // May dispose materials/remove geometrical entities.
    update_drawables_from_source(sourceName, geoData) {  // {{{
        console.debug(geoData);  // XXX
        // update source's materials
        var thisSourceMats = this._materials[sourceName] || {};
        // track used material names
        var matNamesInUse = new Set();
        var materialsToDispose = [];
        // deserialize geodata
        const materialDefinitions = geoData.materials || [];
        geoData.materials.forEach((matDef_) => {
            const { _name: matName
                  , _type: matType
                  , ...matDef } = matDef_;
            if(matNamesInUse.has(matName)) {
                throw new Error(`Material name "${matName}" met`
                    + ` at least twice for source "${sourceName}"`);
            }
            matNamesInUse.add(matName);
            if(thisSourceMats.hasOwnProperty(matName)) {
                if(_.isEqual(thisSourceMats[matName]['matDef'])) {
                    console.debug(`Material "${sourceName}/${matName}" unchanged.`);
                    return;  // skip material construction
                }
                //thisSourceMats[matName].threeJSMaterial.dispose(); // todo: is that needed?
                materialsToDispose.push(thisSourceMats[matName].threeJSMaterial);
                // delete thisSourceMats[matName];  // ?
            }
            // otherwise, create material
            const threeJSMaterials = Materials.make_material(matType, matDef
                , { textureLoader: this._textureLoader });
            thisSourceMats[matName] = {threeJSMaterials, matDef};
            console.debug(`Created material "${sourceName}/${matName}" of type ${matType}`);
        });
        // get materials not used by this source anymore, by
        // comparing material names registered for this source
        // and materials met in this update
        const registeredMatNames = new Set(Object.keys(thisSourceMats));
        const namesToDispose = registeredMatNames.difference(matNamesInUse);
        namesToDispose.forEach((matName) => {
                console.debug(`Material "${sourceName}/${matName}"`
                    + ' is not used anymore -- queued for disposal.');
                materialsToDispose.push(thisSourceMats[matName].threeJSMaterial);
            });
        this._materials[sourceName] = thisSourceMats;
        // update source's geometries
        var thisSourceGeo = this._geometries[sourceName] || {};
        var geomNamesInUse = new Set();
        //var geometriesToDispose = [];  // not needed, as we dispose 'em immediately
        geoData.geometry.forEach((geoDef_) => {
                this.update_geometry_item(geoDef_, geomNamesInUse, thisSourceMats
                    , sourceName, thisSourceGeo);
            });
        this._geometries[sourceName] = thisSourceGeo;
        // TODO: treat materialsToDispose
    }  // }}}
    // Called by watcher on highlight change; should not modify store's values,
    // but follow given ones. Implements changes of the geometrical entities
    // appearance, as defined by `Geometry.js` API.
    update_highlighted_graphics(hlItems, hlItemsOld) {  // {{{
        const added   = Utils.set_difference(hlItems, hlItemsOld);
        const removed = Utils.set_difference(hlItemsOld, hlItems);
        // Get items to un-highlight
        removed.forEach((itemID) => {
                const item = this.get_geometry_item(itemID);
                if(!item) return;
                if(!item.threeJSGeo) return;
                if(!item.threeJSGeo.isGroup) return;
                // disabele visibility for highlighted handle,
                item.threeJSGeo.userData.handles.highlight.visible = false;
                // enable visibility for base handle unless item is in the
                // selection -- in this case enable selected
                //item.threeJSGeo.userData.handles.base.visible = true;
            });
        // Items to highlight
        added.forEach((itemID) => {
                const item = this.get_geometry_item(itemID);
                if(!item) return;
                if(!item.threeJSGeo) return;
                if(!item.threeJSGeo.isGroup) return;
                // enable visibility for highlighted handle, disable for others
                item.threeJSGeo.userData.handles.highlight.visible = true; 
                //item.threeJSGeo.userData.handles.selected.visible = false;
                //item.threeJSGeo.userData.handles.base.visible = false;
            });
        this._render();
    }  // }}}
    // Called on highlighted markers set change
    update_highlighted_markers(highlightedMarkers) {  // {{{
        console.debug(highlightedMarkers);  // XXX
        highlightedMarkers.forEach((idxs, itemID) => {
            console.log(itemID);  // XXX
            const item = this.get_geometry_item(itemID);
            if(!item) return;
            if(!item.threeJSGeo) return;
            if(!item.threeJSGeo.isGroup) return;
            // Handle point markers in a bit of special way -- update
            // colors of highlighted markers using indeces information
                console.debug("updating highlightedMarkers...");  // XXX
                if(item.threeJSGeo.userData.handles.highlight.isPoints) {
                    const clrAttr = item.threeJSGeo.userData.handles.highlight.geometry.getAttribute('color');
                    if(clrAttr) {
                        clrAttr.array.fill(0.0);
                        for(const idx of idxs) {
                            clrAttr.array[3*idx    ] = 1.0;
                            clrAttr.array[3*idx + 1] = 1.0;
                            clrAttr.array[3*idx + 2] = 1.0;
                        }
                        clrAttr.needsUpdate = true;
                    }
                } else {
                    console.warn("Ignoring unsupported by-index marker(?) item");
                }
        });
        this._render();
    }  // }}}
    // Called by watcher on selection change; should not modify store's values,
    // but follow given ones. Implements changes of the geometrical entities
    // appearance, as defined by `Geometry.js` API.
    update_selected_graphics(hlItems, hlItemsOld) {  // {{{
        const added   = Utils.set_difference(hlItems, hlItemsOld);
        const removed = Utils.set_difference(hlItemsOld, hlItems);
        // Get items to un-highlight
        removed.forEach((itemID) => {
                const item = this.get_geometry_item(itemID);
                if(!item) return;
                if(!item.threeJSGeo) return;
                if(!item.threeJSGeo.isGroup) return;
                // disabele visibility for selected handle,
                item.threeJSGeo.userData.handles.selected.visible = false;
                // enable visibility for base handle unless item is in the
                // selection -- in this case enable selected
                //item.threeJSGeo.userData.handles.base.visible = true;
            });
        // Items to highlight
        added.forEach((itemID) => {
                const item = this.get_geometry_item(itemID);
                if(!item) return;
                if(!item.threeJSGeo) return;
                if(!item.threeJSGeo.isGroup) return;
                // enable visibility for highlighted handle, disable for others
                //item.threeJSGeo.userData.handles.highlight.visible = true; 
                item.threeJSGeo.userData.handles.selected.visible = true;
                //item.threeJSGeo.userData.handles.base.visible = false;
            });
        this._render();
    }  // }}}
    get_geometry_item(itemID) {  // {{{
        const [srcID, geoItemID] = Utils.destruct_geo_id(itemID);
        if(!this._geometries.hasOwnProperty(srcID)) return;
        if(!this._geometries[srcID].hasOwnProperty(geoItemID)) return;
        return this._geometries[srcID][geoItemID];
    }  // }}}
}  // class ThreeView

//                  * * *   * * *   * * *

const gDefaultFacetPresets = {
  "Source and transf.groups": {
    facets: [
      "source",
      "transf.group",
    ]
  },
  // ... other default grouping?
};

function normalizeIDs(ids) {
  if (ids === undefined || ids === null)
    return [];
  return Array.isArray(ids) ? ids : [ids];
}

function clonePresets(presets) {
  return Object.fromEntries(
    Object.entries(presets).map(([name, preset]) => [
      name,
      {
        facets: [...(preset.facets ?? [])]
      }
    ])
  );
}

// Vuex state module
const stateModule = {
    namespaced: true,
    state: () => ({
        geoDataBySource: {},
        // Axis-aligned bounding box for objects of interest
        regionOfInterest: [[null, null, null], [null, null, null]],
        // Global axis scales to be applied for geometrical entities as
        // multiplication factors, f_i, r_shown = f_i * r_original.
        axesScales: [1., 1., 1.],  // x, y, z

        //highlightedGeoItemIDs: new Set(),  // highlighted item IDs
        treeHoveredGeoItemIDs: new Set(),  // hovered in tree vwr
        sceneHoveredGeoItemIDs: new Set(),  // hovered on scene

        highlightedMarkers: new Map(), // geoID -> Set(point indeces)
        selectedGeoItemIDs: new Set(),  // selected item IDs
        selectedMarkers: new Map(), // geoID -> Set(point indeces)
        hiddenGeoItemIDs: new Set(),  // ... TODO?

        facetPresets: clonePresets(gDefaultFacetPresets),
        activeFacetPresetName: "Source and transf.groups"
    }),
    mutations: {
        // This mutation gets called from within the API's `add_data_source()'
        // action upon geometry is loaded or updated.
        update_geo_data(state, pl) {
            // CAVEAT: this does not seem to work:
            //state.geoDataBySource[pl.name] = pl.geoData;
            // since the watcher seem to rely on the object ID here and it is
            // not updated; one way to overcome is to rely on JSON.stringify(pl.geoData)
            // or:
            state.geoDataBySource = {
                    ...state.geoDataBySource,
                    [pl.name]: pl.geoData
                };
            console.debug(`mutation:view3d/update_geo_data commited with data from "${pl.name}": "${pl.geoData}"`);  // suceeds
        },

        // Updates region of interest with given point r:float[3]
        update_region_of_interest(state, rs) {
            rs.forEach( r => {
                for(let j = 0; j < 3; ++j) {
                    if( state.regionOfInterest[0][j] === null
                     || state.regionOfInterest[0][j] > r[j] ) {
                        state.regionOfInterest[0][j] = r[j];
                    }
                    if( state.regionOfInterest[1][j] === null
                     || state.regionOfInterest[1][j] < r[j] ) {
                        state.regionOfInterest[1][j] = r[j];
                    }
                }
            });
        },
        // Re-sets region of interest to null
        reset_region_of_interest(state) {
            for(let j = 0; j < 3; ++j) {
                state.regionOfInterest[0][j] = null;
                state.regionOfInterest[1][j] = null;
            }
        },
        // Change the scales
        change_axis_scale(state, pl) {
            const nIdx = {'x':0,'y':1,'z':2}[pl['var']];
            state.axesScales[nIdx] = pl.v;
        },

        //
        // Highlight

        set_tree_hover_geo_items(state, ids) {
          state.treeHoveredGeoItemIDs =
            new Set(normalizeIDs(ids));
        },

        clear_tree_hover_geo_items(state) {
          state.treeHoveredGeoItemIDs = new Set();
        },

        set_scene_hover_geo_items(state, ids) {
          state.sceneHoveredGeoItemIDs =
            new Set(normalizeIDs(ids));
        },

        clear_scene_hover_geo_items(state) {
          state.sceneHoveredGeoItemIDs = new Set();
        },

        highlight_markers(state, { geoID, indices }) {
            const next = new Map(state.highlightedMarkers);
            next.set(geoID, new Set(indices));
            state.highlightedMarkers = next;
        },

        set_highlighted_markers(state, markersByGeoID) {
            state.highlightedMarkers = new Map(
                [...markersByGeoID.entries()].map(([geoID, indices]) => [
                    geoID,
                    new Set(indices),
                ])
            );
        },

        clear_highlighted_markers(state, geoID = null) {
            const next = new Map(state.highlightedMarkers);
            if(geoID === null)
                next.clear();
            else
                next.delete(geoID);
            state.highlightedMarkers = next;
        },

        //
        // Selection

        select_geo_items(state, ids) {
            const next = new Set(state.selectedGeoItemIDs);
            if (typeof ids === "string") {
                next.add(ids);
            } else {
                for (const id of ids)
                    next.add(id);
            }
            state.selectedGeoItemIDs = next;
        },

        unselect_geo_items(state, ids) {
            const next = new Set(state.selectedGeoItemIDs);
            if (typeof ids === "string") {
                next.delete(ids);
            } else {
                for (const id of ids)
                    next.delete(id);
            }
            state.selectedGeoItemIDs = next;
        },

        select_markers(state, { geoID, indices }) {
            const next = new Map(state.selectedMarkers);
            next.set(geoID, new Set(indices));
            state.selectedMarkers = next;
        },

        clear_selected_markers(state, geoID = null) {
            const next = new Map(state.selectedMarkers);
            if(geoID === null)
                next.clear();
            else
                next.delete(geoID);
            state.selectedMarkers = next;
        },

        clear_geo_items_selection(state) {
            state.selectedGeoItemIDs = new Set();
            state.selectedMarkers = new Map();
        },

        //
        // Visibility

        set_geo_items_visibility(
          state,
          {
            ids,
            visible
          }
        ) {
          const next = new Set(state.hiddenGeoItemIDs);

          for (const id of normalizeIDs(ids)) {
            if (visible)
              next.delete(id);
            else
              next.add(id);
          }

          state.hiddenGeoItemIDs = next;
        },

        //
        // Facets

        initialize_facet_presets(
          state,
          {
            presets,
            activePresetName
          }
        ) {
          const normalized = clonePresets(
            presets &&
            Object.keys(presets).length
              ? presets
              : DEFAULT_FACET_PRESETS
          );

          state.facetPresets = normalized;

          if (
            activePresetName &&
            Object.hasOwn(normalized, activePresetName)
          ) {
            state.activeFacetPresetName = activePresetName;
          } else {
            state.activeFacetPresetName =
              Object.keys(normalized)[0];
          }
        },

        activate_facet_preset(state, name) {
          if (Object.hasOwn(state.facetPresets, name))
            state.activeFacetPresetName = name;
        },

        set_active_facet_preset_facets(state, facets) {
          const name = state.activeFacetPresetName;

          if (!name)
            return;

          state.facetPresets = {
            ...state.facetPresets,

            [name]: {
              facets: [...new Set(facets)]
            }
          };
        },

        save_facet_preset(
          state,
          {
            name,
            facets
          }
        ) {
          const trimmedName = name.trim();

          if (!trimmedName)
            return;

          state.facetPresets = {
            ...state.facetPresets,

            [trimmedName]: {
              facets: [...new Set(facets)]
            }
          };

          state.activeFacetPresetName = trimmedName;
        },

        delete_facet_preset(state, name) {
          const names = Object.keys(state.facetPresets);

          if (
            names.length <= 1 ||
            !Object.hasOwn(state.facetPresets, name)
          ) {
            return;
          }

          const next = {
            ...state.facetPresets
          };

          delete next[name];

          state.facetPresets = next;

          if (state.activeFacetPresetName === name)
            state.activeFacetPresetName = Object.keys(next)[0];
        }
    },  // mutations
    actions: {
        // ...
    },
    getters: {
        // See CAVEAT at update_geo_data() mutation; return JSON.stringify(state.geoDataBySource);
        geoData: state => Object.fromEntries(
                Object.entries(state.geoDataBySource).map(([key, pl]) => [key, pl.geometryData])
            ),

        treeHoveredGeoItemIDs: state => state.treeHoveredGeoItemIDs,

        sceneHoveredGeoItemIDs: state => state.sceneHoveredGeoItemIDs,

        highlightedGeoItemIDs: state =>
          new Set([
            ...state.treeHoveredGeoItemIDs,
            ...state.sceneHoveredGeoItemIDs
          ]),

        highlightedMarkers: state => state.highlightedMarkers,

        selectedGeoItemIDs: state => state.selectedGeoItemIDs,
        selectedMarkers: state => state.selectedMarkers,

        hiddenGeoItemIDs: state => state.hiddenGeoItemIDs,
        facetPresets: state => state.facetPresets,

        activeFacetPresetName: state => state.activeFacetPresetName,

        activeFacetPreset: state =>
            state.facetPresets[state.activeFacetPresetName] ??
        {
          facets: []
        },

        // Returns current global transformation (for viewing objects)
        transformationMatrix( state ) {
            const m = new THREE.Matrix3();
            m.set( state.axesScales[0], 0, 0
                 , 0, state.axesScales[1], 0
                 , 0, 0, state.axesScales[2]
                 );
            return m;
        },
        // Axis-aligned bounding box for current region of interest
        aabb(state, getters) {
            if( state.regionOfInterest.flat().some( v => v === null || Number.isNaN(v) ) ) {
                return [Array(3).fill(new THREE.Vector3(NaN, NaN, NaN))];
            }
            const mins = new THREE.Vector3( state.regionOfInterest[0][0]
                                          , state.regionOfInterest[0][1]
                                          , state.regionOfInterest[0][2]
                                       );
            const maxs = new THREE.Vector3( state.regionOfInterest[1][0]
                                          , state.regionOfInterest[1][1]
                                          , state.regionOfInterest[1][2]
                                          );
            const c = mins.clone();
            c.add(maxs).divideScalar(2.);
            return [mins, maxs, c];
        },



        //highlightedMarkersList: state =>
        //    [...state.highlightedMarkers.entries()].map(([geoID, indices]) => ({
        //        geoID,
        //        indices: [...indices],
        //        })),
    }
}  // stateModel

export { ThreeView, stateModule };


